apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleservice
      deployment: canary
  template:
    metadata:
      labels:
        app: simpleservice
        deployment: canary
    spec:
      containers:
        - name: simpleservice
          image: saadgen/??
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
           httpGet:
             path: /live
             port: 8080
             scheme: HTTP
           initialDelaySeconds: 30
           periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: simpleservice-endpoint
  labels:
    app: simpleservice-endpoint
spec:
  selector:
      app: simpleservice
      deployment: canary
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort